GET https://jsonplaceholder.typicode.com/posts

###
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "title":"hello",
    "body":"New post"
}

###
GET  https://jsonplaceholder.typicode.com/posts
